### ISSUE TITLE
99/2 is either 46 or 92, but not 49,5

### ISSUE THREAD

**Issue by IromTypo** [kanderson66/Calculator-Pro#1] opened 2023-12-18 23:03 UTC
That's what it answered for me lol

**Comment by kanderson66** [comment] 2023-12-18 23:26
Are you able to attach a screenshot? Im not able to replicate the issue
![calc](https://github.com/kanderson66/Calculator-Pro/assets/43487922/c56862c5-8bfc-432f-90e3-5b4d1f71772c)

**Comment by IromTypo** [comment] 2023-12-23 11:22
It says 99/2 equals 49,5 in your screenshot

Just saw my answer in the title is wrong lol, it's supposed to be 44,5

**Comment by kanderson66** [comment] 2023-12-23 15:32
Im sorry, can you elaborate on what the issue is? The calculator says that 99/2=49.5, which is correct. 44.5 would be incorrect, as 44.5*2=89. 

Im not sure what you mean in your title either by saying its either 46 or 92? If you're referring to half the xp from level 99, you can find this by inputting the tag 'lvl99' like this: lvl99/2, though this will tell you the xp equivalent, not the level equivalent.

If you can expand on what issue it is youre having, Id be happy to provide a fix if needed :)

**Comment by kanderson66** [comment] 2024-01-04 18:09
Closing issue until further information is provided

**Closed as not planned by kanderson66** 2024-01-04 18:09 UTC
Labels: wontfix
